version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: vaccine-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: vaccine_db
      POSTGRES_USER: vaccine_user
      POSTGRES_PASSWORD: vaccine_pass
      TZ: UTC

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vaccine_user -d vaccine_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local
